spring:
  application:
    name: wlcp-transpiler
server:
   port: 8083
eureka:
   client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}
wlcp-api-url: