spring:
  application:
    name: wlcp-transpiler
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://wlcp-discovery:8761/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
wlcp-api-url: