spring:
  application:
    name: wlcp-transpiler
server:
   port: 8083
eureka:
   client:
    serviceUrl:
      defaultZone: http://wlcp-discovery.local:8761/eureka/
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}
wlcp-api-url: